
#ifndef _PIN_CONFIG_H_
#define _PIN_CONFIG_H_

#define LEFT_OUT_A_PIN PB_11
#define LEFT_OUT_B_PIN PB_10
#define RIGHT_OUT_A_PIN PB_1
#define RIGHT_OUT_B_PIN PB_0
#define LEFT_DOOR_PWM_PIN PA_7
#define RIGHT_DOOR_PWM_PIN PA_6
#define BUTTON_PIN PA_5
#define BUZZER_PIN PA_4
#define LEFT_DOOR_CURRENT_PIN PA_1
#define RIGHT_DOOR_CURRENT_PIN PA_0
#define MOTOR_ACTUATOR_SWITCH_RELAY_PIN PC_15
#define SIGNAL_LAMP_PIN PC_13
#define INTERIOR_LAMP_RELAY_PIN PC_14
#define RIGHT_DOOR_CLOSE_PIN PB_12
#define RIGHT_DOOR_OPEN_PIN PB_13
#define LEFT_DOOR_CLOSE_PIN PB_14
#define LEFT_DOOR_OPEN_PIN PB_15
#define CHECK_CURRENT_PIN PA_8
#define SIM800_TX_PIN PA_9
#define SIM800_RX_PIN PA_10
#define RX480E_4_D0_PIN PA_11
#define RX480E_4_D1_PIN PA_12
#define RX480E_4_D2_PIN PA_15
#define RX480E_4_D3_PIN PB_3
#define RIGHT_MOTOR_COUNTER_PIN PB_8
#define LEFT_MOTOR_COUNTER_PIN PB_9

#define PC_TX_PIN PA_2
#define PC_RX_PIN PA_3


#endif